### ISSUE TITLE
RIOT Exception thrown when spaces are in the file path

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-java-rdf-store#20]
When the attached RDF/XML file is verified using the file path `docfest2021/SPDX DocFest 20210916/ScanCode/scancode-toolkit/time-1.9.tar.gz-extract-clipeu.spdx.rdf`, the following error is generated:

```
11:49:02.369 [main] ERROR org.apache.jena.riot - Bad character in IRI (space): <file:///C:/Users/gary/git/tools-java/SPDX[space]...>
Exception in thread "main" org.apache.jena.riot.RiotException: Bad character in IRI (space): <file:///C:/Users/gary/git/tools-java/SPDX[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:140)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:256)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:273)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.statement(ReaderRIOTRDFXML.java:225)
...
```

Following is the stack trace from where the error is detected in Jena:
```
Thread [main] (Suspended (breakpoint at line 256 in ReaderRIOTRDFXML$HandlerSink))	
	owns: RDFXMLParser  (id=197)	
	ReaderRIOTRDFXML$HandlerSink.convert(AResource) line: 256	
	ReaderRIOTRDFXML$HandlerSink.convert(AResource, AResource, AResource) line: 273	
	ReaderRIOTRDFXML$HandlerSink.statement(AResource, AResource, AResource) line: 225	
	RDFXMLParser(XMLHandler).triple(ANode, ANode, ANode) line: 72	
	WantTopLevelDescription(ParserSupport).triple(ANode, ANode, ANode) line: 233	
	WantTopLevelDescription(WantDescription).aPredAndObj(ANode, ANode) line: 109	
	WantPropertyElement.theObject(ANode) line: 200	
	WantPropertyElement.startElement(String, String, String, Attributes) line: 129	
	RDFXMLParser(XMLHandler).startElement(String, String, String, Attributes) line: 111	
	SAXParserImpl$JAXPSAXParser(AbstractSAXParser).startElement(QName, XMLAttributes, Augmentations) line: not available	
	SAXParserImpl$JAXPSAXParser(AbstractXMLDocumentParser).emptyElement(QName, XMLAttributes, Augmentations) line: not available	
	XMLNSDocumentScannerImpl.scanStartElement() line: not available	
	XMLNSDocumentScannerImpl$NSContentDriver(XMLDocumentFragmentScannerImpl$FragmentContentDriver).next() line: not available	
	XMLNSDocumentScannerImpl(XMLDocumentScannerImpl).next() line: not available	
	XMLNSDocumentScannerImpl.next() line: not available	
	XMLNSDocumentScannerImpl(XMLDocumentFragmentScannerImpl).scanDocument(boolean) line: not available	
	XIncludeAwareParserConfiguration(XML11Configuration).parse(boolean) line: not available	
	XIncludeAwareParserConfiguration(XML11Configuration).parse(XMLInputSource) line: not available	
	SAXParserImpl$JAXPSAXParser(XMLParser).parse(XMLInputSource) line: not available	
	SAXParserImpl$JAXPSAXParser(AbstractSAXParser).parse(InputSource) line: not available	
	SAXParserImpl$JAXPSAXParser.parse(InputSource) line: not available	
	RDFXMLParser.parse(InputSource, String) line: 101	
	ARP.load(InputStream, String) line: 118	
	ReaderRIOTRDFXML.parse() line: 188	
	ReaderRIOTRDFXML.read(InputStream, String, ContentType, StreamRDF, Context) line: 86	
	RDFParser.read(ReaderRIOT, InputStream, Reader, String, Context, ContentType, StreamRDF) line: 352	
	RDFParser.parseNotUri(StreamRDF) line: 342	
	RDFParser.parse(StreamRDF) line: 291	
	RDFParserBuilder.parse(StreamRDF) line: 506	
	RDFDataMgr.parseFromInputStream(StreamRDF, InputStream, String, Lang, Context) line: 870	
	RDFDataMgr.read(Graph, InputStream, String, Lang) line: 268	
	RDFDataMgr.read(Model, InputStream, String, Lang) line: 254	
	RDFReaderRIOT.read(Model, InputStream, String) line: 69	
	ModelCom.read(InputStream, String, String) line: 305	
	RdfStore.deSerialize(InputStream, boolean) line: 521	
	Verify.verify(String, SerFileType) line: 118	
	Verify.main(String[]) line: 70	
``
[time-1.9.tar.gz-extract-clipeu.spdx.rdf.txt](https://github.com/spdx/spdx-java-rdf-store/files/7187890/time-1.9.tar.gz-extract-clipeu.spdx.rdf.txt)
`

**Comment by goneall** [comment]
This was actually caused by an invalid IRI in the RDF/XML file at line 2858:

```
    <ns1:name rdf:resource="SPDX Document created by ScanCode Toolkit"/>
```

resource needs to be a valid IRI - any spaces need to be escaped.
